### ISSUE TITLE
404 error when using Homebrew

### ISSUE THREAD

**Issue by OskarPersson** [KittyKatt/screenFetch#273]
`brew install screenfetch` returns a 404 error when trying to download from https://codeload.github.com/KittyKatt/screenFetch/tar.gz/3.7.0

    ==> Downloading https://github.com/KittyKatt/screenFetch/archive/3.7.0.tar.gz
    ==> Downloading from https://codeload.github.com/KittyKatt/screenFetch/tar.gz/3.7.0

    curl: (22) The requested URL returned error: 404 Not Found

**Comment by darealshinji** [comment]
Download URL is https://github.com/KittyKatt/screenFetch/archive/v3.7.0.tar.gz
Or https://github.com/KittyKatt/screenFetch/archive/master.tar.gz for a current master branch snapshot.

Maybe you could send a fix to https://github.com/Homebrew/homebrew since KittyKatt doesn't maintain any of the provided distribution packages himself (afaik).
I'd do it myself, but I don't use OSX and therefor can't check if my PR would really fix it :(

**Comment by OskarPersson** [comment]
Yeah that seems correct, you can send the pull request :)

**Comment by darealshinji** [comment]
I think this issue can be closed now: https://github.com/Homebrew/homebrew/commit/fc80d99253ac2b357486ada4bdf8d12f383795a4

**Comment by KittyKatt** [comment]
Awesome, thanks guys! Yeah, I don't deal with any of the packages myself. I let users make their own distribution packages and maintain them. :)
