### ISSUE TITLE
2 Bugs at CPU and RAM

### ISSUE THREAD

**Issue by LucyDemooon** [KittyKatt/screenFetch#386]
hey

have found 2 BUGS at the CPU frequency and Ram.
Ram is 1GB to high.
and CPU frequency is incorrect 
see pic http://www.directupload.net/file/d/4487/vq9o55ar_png.htm

**Comment by tobbez** [comment]
The RAM is correct. 1GiB is 1024MiB:`32117/1024 = 31.364 ≈ 31.4`

**Comment by LucyDemooon** [comment]
I do not mean the maximum value
but the current value

**Comment by tobbez** [comment]
No idea where the system monitor you use as reference gets its data. Anyway...

If one wants to calculate it the way it's currently done then rather than
```
usedmem = MemTotal - MemFree - Buffers - Cached
```
it looks like it should be:
```
usedmem = MemTotal + Shmem - MemFree - Buffers - Cached - SReclaimable
```

Shmem covers e.g. tmpfs, which is included in cache, but is not actually reclaimable.

SReclaimable is reclaimable part of Slab.

Optionally SwapCached can be subtracted as well - it's memory that was swapped out, is swapped in again, but is still also left in the swap. Essentially it can be swapped out "for free". Doesn't seem quite right to include though (and doesn't seem to be in other tools).

On kernels 3.14 and later, the MemAvailable value could possibly be used ([commit](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773)).

Here's some related links:
* https://github.com/brndnmtthws/conky/issues/130
* https://github.com/hishamhm/htop/pull/313
*  https://gitlab.com/procps-ng/procps/commit/05d751c4f076a2f0118b914c5e51cfbb4762ad8e
* https://support.zabbix.com/browse/ZBX-9142
* https://github.com/brndnmtthws/conky/pull/54
* https://bitbucket.org/tildeslash/monit/issues/71
